apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: identity-service

  template:
    metadata:
      labels:
        app: identity-service

    spec:
      containers:
        - name: identity-service
          image: identity-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8083

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/circleguard_identity

            - name: SPRING_DATASOURCE_USERNAME
              value: admin

            - name: SPRING_DATASOURCE_PASSWORD
              value: password

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: host.docker.internal:9092
