spring:
  application:
    name: circleguard-gateway-service
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "this-is-a-super-long-gateway-secret-key-for-testing-123456789"
  expiration: 3600000

qr:
  secret: "this-is-a-super-long-qr-secret-key-for-testing-123456789"
  expiration: 300

server:
  port: 8087
