apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: simongarcia01/notification-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8082

          env:
            - name: AUTH_API_URL
              value: http://auth-service:8180
