apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: prod
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8087
      targetPort: 8087
      nodePort: 32087
  type: NodePort
