apiVersion: v1
kind: Secret
metadata:
  name: circleguard-db-credentials
  namespace: prod
  labels:
    app.kubernetes.io/part-of: circleguard
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: circleguard-ldap-credentials
  namespace: prod
  labels:
    app.kubernetes.io/part-of: circleguard
type: Opaque
stringData:
  SPRING_LDAP_USERNAME: "cn=admin,dc=circleguard,dc=edu"
  SPRING_LDAP_PASSWORD: "admin"

---
apiVersion: v1
kind: Secret
metadata:
  name: circleguard-auth-keys
  namespace: prod
  labels:
    app.kubernetes.io/part-of: circleguard
type: Opaque
stringData:
  JWT_SECRET: "my-super-secret-prod-key-32-chars-long-12345678"
  QR_SECRET: "my-qr-secret-key-for-prod-1234567890"

---
apiVersion: v1
kind: Secret
metadata:
  name: circleguard-neo4j-credentials
  namespace: prod
  labels:
    app.kubernetes.io/part-of: circleguard
type: Opaque
stringData:
  NEO4J_AUTH: "neo4j/password"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "password"
