apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-service
  namespace: dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: form-service

  template:
    metadata:
      labels:
        app: form-service

    spec:
      containers:
        - name: form-service
          image: simongarcia01/form-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8086

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/form_db

            - name: SPRING_DATASOURCE_USERNAME
              value: admin

            - name: SPRING_DATASOURCE_PASSWORD
              value: password

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
