apiVersion: v1
kind: Service
metadata:
  name: form-service
  namespace: dev

spec:
  selector:
    app: form-service

  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 30086

  type: NodePort
