apiVersion: v1
kind: Service
metadata:
  name: form-service
  namespace: stage
spec:
  selector:
    app: form-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 31086
  type: NodePort
