apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: stage
data:
  init-db.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE identity_db;
    CREATE DATABASE promotion_db;
    CREATE DATABASE dashboard_db;
    CREATE DATABASE form_db;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: circleguard-db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-db-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: stage
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
