apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      containers:
        - name: promotion-service
          image: simongarcia01/promotion-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8088

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/circleguard_promotion

            - name: SPRING_DATASOURCE_USERNAME
              value: admin

            - name: SPRING_DATASOURCE_PASSWORD
              value: password

            - name: SPRING_NEO4J_URI
              value: bolt://host.docker.internal:7687

            - name: SPRING_NEO4J_AUTHENTICATION_USERNAME
              value: neo4j

            - name: SPRING_NEO4J_AUTHENTICATION_PASSWORD
              value: password

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: host.docker.internal:9092

            - name: SPRING_DATA_REDIS_HOST
              value: host.docker.internal

            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
