apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      serviceAccountName: identity-service
      containers:
        - name: identity-service
          image: simongarcia01/identity-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stage
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/identity_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: circleguard-db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-db-credentials
                  key: POSTGRES_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: VAULT_SECRET
              value: "746573742d7365637265742d33322d63686172732d6c6f6e672d313233343536"
            - name: VAULT_SALT
              value: "deadbeef"
            - name: VAULT_HASH_SALT
              value: "12345678"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-auth-keys
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
