spring:
  application:
    name: circleguard-notification-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: ${MAIL_HOST:dummy}
    port: ${MAIL_PORT:0}

auth:
  api:
    url: ${AUTH_API_URL:http://auth-service:8180}

jwt:
  secret: ${JWT_SECRET:my-super-secret-dev-key-32-chars-long-12345678}
  expiration: ${JWT_EXPIRATION:3600000}

qr:
  secret: ${QR_SECRET:this-is-a-super-long-notification-qr-secret-123456}
  expiration: ${QR_EXPIRATION:300}

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: circleguard-notification-service
      environment: ${ENVIRONMENT:dev}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger-service:4318/v1/traces

logging:
  pattern:
    console: "%d{ISO8601} %5p [%X{traceId:-},%X{spanId:-}] [circleguard-notification-service] %logger{36} --- %m%n"
